/** @type {import('tailwindcss').Config} */
module.exports = {
  content: [
    "./pages/**/*.{js,ts,jsx,tsx,mdx}",
    "./components/**/*.{js,ts,jsx,tsx,mdx}",
    "./app/**/*.{js,ts,jsx,tsx,mdx}",
  ],
  darkMode: ["class"],
  theme: {
    extend: {
      colors: {
        prose: {
          body: "hsl(var(--prose-body))",
          selection: "hsl(var(--prose-selection))",
          headings: "hsl(var(--prose-headings))",
          lead: "hsl(var(--prose-lead))",
          underline: "hsl(var(--prose-underline))",
          links: "hsl(var(--prose-links))",
          "links-muted": "hsl(var(--prose-links-muted))",
          bold: "hsl(var(--prose-bold))",
          counters: "hsl(var(--prose-counters))",
          bullets: "hsl(var(--prose-bullets))",
          hr: "hsl(var(--prose-hr))",
          quotes: "hsl(var(--prose-quotes))",
          "quote-borders": "hsl(var(--prose-quote-borders))",
          captions: "hsl(var(--prose-captions))",
          code: "hsl(var(--prose-code))",
          "code-bg": "hsl(var(--prose-code-bg))",
          "pre-code": "hsl(var(--prose-pre-code))",
          "pre-bg": "hsl(var(--prose-pre-bg))",
          "th-borders": "hsl(var(--prose-th-borders))",
          "td-borders": "hsl(var(--prose-td-borders))",
        },
      },
      fontFamily: {
        sans: [
          "var(--font-inter)",
          "ui-sans-serif",
          "system-ui",
          "-apple-system",
          "BlinkMacSystemFont",
          "Segoe UI",
          "Roboto",
          "Helvetica Neue",
          "Arial",
          "Noto Sans",
          "sans-serif",
          "Apple Color Emoji",
          "Segoe UI Emoji",
          "Segoe UI Symbol",
          "Noto Color Emoji",
        ],
        mono: [
          "var(--font-sfMono)",
          "ui-monospace",
          "SFMono-Regular",
          "Menlo",
          "Monaco",
          "Consolas",
          "Liberation Mono",
          "Courier New",
          "monospace",
        ],
      },
    },
  },
};
